
import {
    IconAbsoluteStroked,
    IconActivity,
    IconAlarm,
    IconAlertCircle,
    IconAlertTriangle,
    IconAlignBottom,
    IconAlignCenter,
    IconAlignCenterVertical,
    IconAlignHCenterStroked,
    IconAlignHLeftStroked,
    IconAlignHRightStroked,
    IconAlignJustify,
    IconAlignLeft,
    IconAlignRight,
    IconAlignTop,
    IconAlignVBotStroked,
    IconAlignVBottomStroked,
    IconAlignVCenterStroked,
    IconAlignVTopStroked,
    IconApartment,
    IconAppCenter,
    IconApps,
    IconArchive,
    IconArrowDown,
    IconArrowDownLeft,
    IconArrowDownRight,
    IconArrowLeft,
    IconArrowRight,
    IconArrowUp,
    IconArrowUpLeft,
    IconArrowUpRight,
    IconArticle,
    IconAscend,
    IconAt,
    IconBackTop,
    IconBackward,
    IconBarChartHStroked,
    IconBarChartVStroked,
    IconBeaker,
    IconBell,
    IconBellStroked,
    IconBold,
    IconBolt,
    IconBookH5Stroked,
    IconBookOpenStroked,
    IconBookStroked,
    IconBookmark,
    IconBookmarkAddStroked,
    IconBookmarkDeleteStroked,
    IconBottomCenterStroked,
    IconBottomLeftStroked,
    IconBottomRightStroked,
    IconBox,
    IconBrackets,
    IconBranch,
    IconBriefStroked,
    IconBriefcase,
    IconBulb,
    IconButtonStroked,
    IconBytedanceLogo,
    IconCalendar,
    IconCalendarClock,
    IconCamera,
    IconCandlestickChartStroked,
    IconCaretdown,
    IconCaretup,
    IconCarouselStroked,
    IconCart,
    IconCaseSensitive,
    IconCenterLeftStroked,
    IconCenterRightStroked,
    IconChainStroked,
    IconCheckChoiceStroked,
    IconCheckCircleStroked,
    IconCheckList,
    IconCheckboxIndeterminate,
    IconCheckboxTick,
    IconChecklistStroked,
    IconChevronDown,
    IconChevronDownStroked,
    IconChevronLeft,
    IconChevronRight,
    IconChevronRightStroked,
    IconChevronUp,
    IconChevronUpDown,
    IconClear,
    IconClock,
    IconClose,
    IconCloud,
    IconCloudStroked,
    IconCloudUploadStroked,
    IconCode,
    IconCodeStroked,
    IconCoinMoneyStroked,
    IconColorPalette,
    IconColumnsStroked,
    IconCommand,
    IconComment,
    IconCommentStroked,
    IconComponent,
    IconComponentPlaceholderStroked,
    IconComponentStroked,
    IconContrast,
    IconCopy,
    IconCopyAdd,
    IconCopyStroked,
    IconCornerRadiusStroked,
    IconCreditCard,
    IconCrop,
    IconCrossCircleStroked,
    IconCrossStroked,
    IconCrown,
    IconCustomerSupport,
    IconCustomerSupportStroked,
    IconCustomize,
    IconDelete,
    IconDeleteStroked,
    IconDescend,
    IconDescend2,
    IconDesktop,
    IconDisc,
    IconDislikeThumb,
    IconDivide,
    IconDongchediLogo,
    IconDoubleChevronLeft,
    IconDoubleChevronRight,
    IconDownCircleStroked,
    IconDownload,
    IconDownloadStroked,
    IconDuration,
    IconEdit,
    IconEdit2Stroked,
    IconEditStroked,
    IconElementStroked,
    IconEmoji,
    IconExit,
    IconExpand,
    IconExport,
    IconExternalOpen,
    IconExternalOpenStroked,
    IconEyeClosed,
    IconEyeClosedSolid,
    IconEyeOpened,
    IconFacebook,
    IconFaceuLogo,
    IconFastForward,
    IconFastFoward,
    IconFavoriteList,
    IconFeishuLogo,
    IconFemale,
    IconFigma,
    IconFile,
    IconFillStroked,
    IconFilledArrowDown,
    IconFilledArrowUp,
    IconFilpVertical,
    IconFilter,
    IconFingerLeftStroked,
    IconFixedStroked,
    IconFlag,
    IconFlipHorizontal,
    IconFlowChartStroked,
    IconFolder,
    IconFolderOpen,
    IconFolderStroked,
    IconFollowStroked,
    IconFont,
    IconFontColor,
    IconForward,
    IconForwardStroked,
    IconFullScreenStroked,
    IconGallery,
    IconGift,
    IconGiftStroked,
    IconGit,
    IconGithubLogo,
    IconGitlabLogo,
    IconGlobe,
    IconGlobeStroke,
    IconGridRectangle,
    IconGridSquare,
    IconGridStroked,
    IconGridView,
    IconGridView1,
    IconH1,
    IconH2,
    IconH3,
    IconH4,
    IconH5,
    IconH6,
    IconH7,
    IconH8,
    IconH9,
    IconHandle,
    IconHash,
    IconHeartStroked,
    IconHelm,
    IconHelpCircle,
    IconHelpCircleStroked,
    IconHistogram,
    IconHistory,
    IconHn,
    IconHome,
    IconHomeStroked,
    IconHorn,
    IconHourglass,
    IconHourglassStroked,
    IconIdCard,
    IconIdentity,
    IconImage,
    IconImageStroked,
    IconImport,
    IconInbox,
    IconIndenpentCornersStroked,
    IconIndentLeft,
    IconIndentRight,
    IconIndependentCornersStroked,
    IconInfoCircle,
    IconInherit,
    IconInheritStroked,
    IconInnerSectionStroked,
    IconInstagram,
    IconInteractiveStroked,
    IconInviteStroked,
    IconItalic,
    IconJianying,
    IconKanban,
    IconKey,
    IconKeyStroked,
    IconLanguage,
    IconLayers,
    IconLeftCircleStroked,
    IconLightningStroked,
    IconLikeHeart,
    IconLikeThumb,
    IconLineChartStroked,
    IconLineHeight,
    IconLink,
    IconList,
    IconListView,
    IconLive,
    IconLoading,
    IconLock,
    IconLockStroked,
    IconLoopTextStroked,
    IconMail,
    IconMailStroked,
    IconMailStroked1,
    IconMale,
    IconMapPin,
    IconMapPinStroked,
    IconMarginLeftStroked,
    IconMarginStroked,
    IconMark,
    IconMaximize,
    IconMember,
    IconMenu,
    IconMicrophone,
    IconMicrophoneOff,
    IconMinimize,
    IconMinus,
    IconMinusCircle,
    IconMinusCircleStroked,
    IconMinusStroked,
    IconModalStroked,
    IconMoneyExchangeStroked,
    IconMonitorStroked,
    IconMoon,
    IconMore,
    IconMoreStroked,
    IconMusic,
    IconMusicNoteStroked,
    IconMute,
    IconNineGridStroked,
    IconNoteMoneyStroked,
    IconOption,
    IconOrderedList,
    IconOrderedListStroked,
    IconPaperclip,
    IconPause,
    IconPercentage,
    IconPhone,
    IconPhoneStroke,
    IconPieChart2Stroked,
    IconPieChartStroked,
    IconPiechartH5Stroked,
    IconPipixiaLogo,
    IconPlay,
    IconPlayCircle,
    IconPlus,
    IconPlusCircle,
    IconPlusCircleStroked,
    IconPlusStroked,
    IconPriceTag,
    IconPrint,
    IconPrizeStroked,
    IconPulse,
    IconPuzzle,
    IconQingyan,
    IconQrCode,
    IconQuit,
    IconQuote,
    IconRadio,
    IconRankingCardStroked,
    IconRealSizeStroked,
    IconRedo,
    IconRedoStroked,
    IconRefresh,
    IconRefresh2,
    IconRegExp,
    IconReply,
    IconReplyStroked,
    IconResso,
    IconRestart,
    IconRingChartStroked,
    IconRotate,
    IconRotationStroked,
    IconRoute,
    IconRowsStroked,
    IconSafe,
    IconSave,
    IconSaveStroked,
    IconScan,
    IconScissors,
    IconSearch,
    IconSearchStroked,
    IconSectionStroked,
    IconSemiLogo,
    IconSend,
    IconSendMsgStroked,
    IconSendStroked,
    IconServer,
    IconServerStroked,
    IconSetting,
    IconSettingStroked,
    IconShareMoneyStroked,
    IconShareStroked,
    IconShield,
    IconShieldStroked,
    IconShift,
    IconShoppingBag,
    IconShrink,
    IconShrinkScreenStroked,
    IconSidebar,
    IconSignal,
    IconSimilarity,
    IconSmallTriangleDown,
    IconSmallTriangleLeft,
    IconSmallTriangleRight,
    IconSmallTriangleTop,
    IconSmartphoneCheckStroked,
    IconSmartphoneStroked,
    IconSong,
    IconSonicStroked,
    IconSort,
    IconSortStroked,
    IconSourceControl,
    IconSpin,
    IconStackBarChartStroked,
    IconStar,
    IconStarStroked,
    IconStop,
    IconStopwatchStroked,
    IconStrikeThrough,
    IconSun,
    IconSync,
    IconTabArrowStroked,
    IconTabsStroked,
    IconTaskMoneyStroked,
    IconTemplate,
    IconTemplateStroked,
    IconTerminal,
    IconTestScoreStroked,
    IconText,
    IconTextRectangle,
    IconTextStroked,
    IconThumbUpStroked,
    IconTick,
    IconTickCircle,
    IconTicketCodeExchangeStroked,
    IconTicketCodeStroked,
    IconTiktokLogo,
    IconTop,
    IconTopCenterStroked,
    IconTopLeftStroked,
    IconTopRightStroked,
    IconTopbuzzLogo,
    IconToutiaoLogo,
    IconTransparentStroked,
    IconTreeTriangleDown,
    IconTreeTriangleRight,
    IconTriangleArrow,
    IconTriangleArrowVertical,
    IconTriangleDown,
    IconTriangleUp,
    IconTrueFalseStroked,
    IconTvCheckedStroked,
    IconTwitter,
    IconTypograph,
    IconUnChainStroked,
    IconUnderline,
    IconUndo,
    IconUnlink,
    IconUnlock,
    IconUnlockStroked,
    IconUpload,
    IconUploadError,
    IconUser,
    IconUserAdd,
    IconUserCardPhone,
    IconUserCardVideo,
    IconUserCircle,
    IconUserCircleStroked,
    IconUserGroup,
    IconUserListStroked,
    IconUserSetting,
    IconUserStroked,
    IconVennChartStroked,
    IconVerify,
    IconVideo,
    IconVideoDouyinStroked,
    IconVideoListStroked,
    IconVideoStroked,
    IconVideoUrlStroked,
    IconVigoLogo,
    IconVolume1,
    IconVolume2,
    IconVolumnSilent,
    IconVoteStroked,
    IconVoteVideoStroked,
    IconWeibo,
    IconWholeWord,
    IconWifi,
    IconWindowAdaptionStroked,
    IconWrench,
    IconXiguaLogo,
    IconYoutube,
} from '@douyinfe/semi-icons';

interface Icon {
    [propName: string]: JSX.Element
}

const icon: Icon = {
    IconAbsoluteStroked: <IconAbsoluteStroked />,
    IconActivity: <IconActivity />,
    IconAlarm: <IconAlarm />,
    IconAlertCircle: <IconAlertCircle />,
    IconAlertTriangle: <IconAlertTriangle />,
    IconAlignBottom: <IconAlignBottom />,
    IconAlignCenter: <IconAlignCenter />,
    IconAlignCenterVertical: <IconAlignCenterVertical />,
    IconAlignHCenterStroked: <IconAlignHCenterStroked />,
    IconAlignHLeftStroked: <IconAlignHLeftStroked />,
    IconAlignHRightStroked: <IconAlignHRightStroked />,
    IconAlignJustify: <IconAlignJustify />,
    IconAlignLeft: <IconAlignLeft />,
    IconAlignRight: <IconAlignRight />,
    IconAlignTop: <IconAlignTop />,
    IconAlignVBotStroked: <IconAlignVBotStroked />,
    IconAlignVBottomStroked: <IconAlignVBottomStroked />,
    IconAlignVCenterStroked: <IconAlignVCenterStroked />,
    IconAlignVTopStroked: <IconAlignVTopStroked />,
    IconApartment: <IconApartment />,
    IconAppCenter: <IconAppCenter />,
    IconApps: <IconApps />,
    IconArchive: <IconArchive />,
    IconArrowDown: <IconArrowDown />,
    IconArrowDownLeft: <IconArrowDownLeft />,
    IconArrowDownRight: <IconArrowDownRight />,
    IconArrowLeft: <IconArrowLeft />,
    IconArrowRight: <IconArrowRight />,
    IconArrowUp: <IconArrowUp />,
    IconArrowUpLeft: <IconArrowUpLeft />,
    IconArrowUpRight: <IconArrowUpRight />,
    IconArticle: <IconArticle />,
    IconAscend: <IconAscend />,
    IconAt: <IconAt />,
    IconBackTop: <IconBackTop />,
    IconBackward: <IconBackward />,
    IconBarChartHStroked: <IconBarChartHStroked />,
    IconBarChartVStroked: <IconBarChartVStroked />,
    IconBeaker: <IconBeaker />,
    IconBell: <IconBell />,
    IconBellStroked: <IconBellStroked />,
    IconBold: <IconBold />,
    IconBolt: <IconBolt />,
    IconBookH5Stroked: <IconBookH5Stroked />,
    IconBookOpenStroked: <IconBookOpenStroked />,
    IconBookStroked: <IconBookStroked />,
    IconBookmark: <IconBookmark />,
    IconBookmarkAddStroked: <IconBookmarkAddStroked />,
    IconBookmarkDeleteStroked: <IconBookmarkDeleteStroked />,
    IconBottomCenterStroked: <IconBottomCenterStroked />,
    IconBottomLeftStroked: <IconBottomLeftStroked />,
    IconBottomRightStroked: <IconBottomRightStroked />,
    IconBox: <IconBox />,
    IconBrackets: <IconBrackets />,
    IconBranch: <IconBranch />,
    IconBriefStroked: <IconBriefStroked />,
    IconBriefcase: <IconBriefcase />,
    IconBulb: <IconBulb />,
    IconButtonStroked: <IconButtonStroked />,
    IconBytedanceLogo: <IconBytedanceLogo />,
    IconCalendar: <IconCalendar />,
    IconCalendarClock: <IconCalendarClock />,
    IconCamera: <IconCamera />,
    IconCandlestickChartStroked: <IconCandlestickChartStroked />,
    IconCaretdown: <IconCaretdown />,
    IconCaretup: <IconCaretup />,
    IconCarouselStroked: <IconCarouselStroked />,
    IconCart: <IconCart />,
    IconCaseSensitive: <IconCaseSensitive />,
    IconCenterLeftStroked: <IconCenterLeftStroked />,
    IconCenterRightStroked: <IconCenterRightStroked />,
    IconChainStroked: <IconChainStroked />,
    IconCheckChoiceStroked: <IconCheckChoiceStroked />,
    IconCheckCircleStroked: <IconCheckCircleStroked />,
    IconCheckList: <IconCheckList />,
    IconCheckboxIndeterminate: <IconCheckboxIndeterminate />,
    IconCheckboxTick: <IconCheckboxTick />,
    IconChecklistStroked: <IconChecklistStroked />,
    IconChevronDown: <IconChevronDown />,
    IconChevronDownStroked: <IconChevronDownStroked />,
    IconChevronLeft: <IconChevronLeft />,
    IconChevronRight: <IconChevronRight />,
    IconChevronRightStroked: <IconChevronRightStroked />,
    IconChevronUp: <IconChevronUp />,
    IconChevronUpDown: <IconChevronUpDown />,
    IconClear: <IconClear />,
    IconClock: <IconClock />,
    IconClose: <IconClose />,
    IconCloud: <IconCloud />,
    IconCloudStroked: <IconCloudStroked />,
    IconCloudUploadStroked: <IconCloudUploadStroked />,
    IconCode: <IconCode />,
    IconCodeStroked: <IconCodeStroked />,
    IconCoinMoneyStroked: <IconCoinMoneyStroked />,
    IconColorPalette: <IconColorPalette />,
    IconColumnsStroked: <IconColumnsStroked />,
    IconCommand: <IconCommand />,
    IconComment: <IconComment />,
    IconCommentStroked: <IconCommentStroked />,
    IconComponent: <IconComponent />,
    IconComponentPlaceholderStroked: <IconComponentPlaceholderStroked />,
    IconComponentStroked: <IconComponentStroked />,
    IconContrast: <IconContrast />,
    IconCopy: <IconCopy />,
    IconCopyAdd: <IconCopyAdd />,
    IconCopyStroked: <IconCopyStroked />,
    IconCornerRadiusStroked: <IconCornerRadiusStroked />,
    IconCreditCard: <IconCreditCard />,
    IconCrop: <IconCrop />,
    IconCrossCircleStroked: <IconCrossCircleStroked />,
    IconCrossStroked: <IconCrossStroked />,
    IconCrown: <IconCrown />,
    IconCustomerSupport: <IconCustomerSupport />,
    IconCustomerSupportStroked: <IconCustomerSupportStroked />,
    IconCustomize: <IconCustomize />,
    IconDelete: <IconDelete />,
    IconDeleteStroked: <IconDeleteStroked />,
    IconDescend: <IconDescend />,
    IconDescend2: <IconDescend2 />,
    IconDesktop: <IconDesktop />,
    IconDisc: <IconDisc />,
    IconDislikeThumb: <IconDislikeThumb />,
    IconDivide: <IconDivide />,
    IconDongchediLogo: <IconDongchediLogo />,
    IconDoubleChevronLeft: <IconDoubleChevronLeft />,
    IconDoubleChevronRight: <IconDoubleChevronRight />,
    IconDownCircleStroked: <IconDownCircleStroked />,
    IconDownload: <IconDownload />,
    IconDownloadStroked: <IconDownloadStroked />,
    IconDuration: <IconDuration />,
    IconEdit: <IconEdit />,
    IconEdit2Stroked: <IconEdit2Stroked />,
    IconEditStroked: <IconEditStroked />,
    IconElementStroked: <IconElementStroked />,
    IconEmoji: <IconEmoji />,
    IconExit: <IconExit />,
    IconExpand: <IconExpand />,
    IconExport: <IconExport />,
    IconExternalOpen: <IconExternalOpen />,
    IconExternalOpenStroked: <IconExternalOpenStroked />,
    IconEyeClosed: <IconEyeClosed />,
    IconEyeClosedSolid: <IconEyeClosedSolid />,
    IconEyeOpened: <IconEyeOpened />,
    IconFacebook: <IconFacebook />,
    IconFaceuLogo: <IconFaceuLogo />,
    IconFastForward: <IconFastForward />,
    IconFastFoward: <IconFastFoward />,
    IconFavoriteList: <IconFavoriteList />,
    IconFeishuLogo: <IconFeishuLogo />,
    IconFemale: <IconFemale />,
    IconFigma: <IconFigma />,
    IconFile: <IconFile />,
    IconFillStroked: <IconFillStroked />,
    IconFilledArrowDown: <IconFilledArrowDown />,
    IconFilledArrowUp: <IconFilledArrowUp />,
    IconFilpVertical: <IconFilpVertical />,
    IconFilter: <IconFilter />,
    IconFingerLeftStroked: <IconFingerLeftStroked />,
    IconFixedStroked: <IconFixedStroked />,
    IconFlag: <IconFlag />,
    IconFlipHorizontal: <IconFlipHorizontal />,
    IconFlowChartStroked: <IconFlowChartStroked />,
    IconFolder: <IconFolder />,
    IconFolderOpen: <IconFolderOpen />,
    IconFolderStroked: <IconFolderStroked />,
    IconFollowStroked: <IconFollowStroked />,
    IconFont: <IconFont />,
    IconFontColor: <IconFontColor />,
    IconForward: <IconForward />,
    IconForwardStroked: <IconForwardStroked />,
    IconFullScreenStroked: <IconFullScreenStroked />,
    IconGallery: <IconGallery />,
    IconGift: <IconGift />,
    IconGiftStroked: <IconGiftStroked />,
    IconGit: <IconGit />,
    IconGithubLogo: <IconGithubLogo />,
    IconGitlabLogo: <IconGitlabLogo />,
    IconGlobe: <IconGlobe />,
    IconGlobeStroke: <IconGlobeStroke />,
    IconGridRectangle: <IconGridRectangle />,
    IconGridSquare: <IconGridSquare />,
    IconGridStroked: <IconGridStroked />,
    IconGridView: <IconGridView />,
    IconGridView1: <IconGridView1 />,
    IconH1: <IconH1 />,
    IconH2: <IconH2 />,
    IconH3: <IconH3 />,
    IconH4: <IconH4 />,
    IconH5: <IconH5 />,
    IconH6: <IconH6 />,
    IconH7: <IconH7 />,
    IconH8: <IconH8 />,
    IconH9: <IconH9 />,
    IconHandle: <IconHandle />,
    IconHash: <IconHash />,
    IconHeartStroked: <IconHeartStroked />,
    IconHelm: <IconHelm />,
    IconHelpCircle: <IconHelpCircle />,
    IconHelpCircleStroked: <IconHelpCircleStroked />,
    IconHistogram: <IconHistogram />,
    IconHistory: <IconHistory />,
    IconHn: <IconHn />,
    IconHome: <IconHome />,
    IconHomeStroked: <IconHomeStroked />,
    IconHorn: <IconHorn />,
    IconHourglass: <IconHourglass />,
    IconHourglassStroked: <IconHourglassStroked />,
    IconIdCard: <IconIdCard />,
    IconIdentity: <IconIdentity />,
    IconImage: <IconImage />,
    IconImageStroked: <IconImageStroked />,
    IconImport: <IconImport />,
    IconInbox: <IconInbox />,
    IconIndenpentCornersStroked: <IconIndenpentCornersStroked />,
    IconIndentLeft: <IconIndentLeft />,
    IconIndentRight: <IconIndentRight />,
    IconIndependentCornersStroked: <IconIndependentCornersStroked />,
    IconInfoCircle: <IconInfoCircle />,
    IconInherit: <IconInherit />,
    IconInheritStroked: <IconInheritStroked />,
    IconInnerSectionStroked: <IconInnerSectionStroked />,
    IconInstagram: <IconInstagram />,
    IconInteractiveStroked: <IconInteractiveStroked />,
    IconInviteStroked: <IconInviteStroked />,
    IconItalic: <IconItalic />,
    IconJianying: <IconJianying />,
    IconKanban: <IconKanban />,
    IconKey: <IconKey />,
    IconKeyStroked: <IconKeyStroked />,
    IconLanguage: <IconLanguage />,
    IconLayers: <IconLayers />,
    IconLeftCircleStroked: <IconLeftCircleStroked />,
    IconLightningStroked: <IconLightningStroked />,
    IconLikeHeart: <IconLikeHeart />,
    IconLikeThumb: <IconLikeThumb />,
    IconLineChartStroked: <IconLineChartStroked />,
    IconLineHeight: <IconLineHeight />,
    IconLink: <IconLink />,
    IconList: <IconList />,
    IconListView: <IconListView />,
    IconLive: <IconLive />,
    IconLoading: <IconLoading />,
    IconLock: <IconLock />,
    IconLockStroked: <IconLockStroked />,
    IconLoopTextStroked: <IconLoopTextStroked />,
    IconMail: <IconMail />,
    IconMailStroked: <IconMailStroked />,
    IconMailStroked1: <IconMailStroked1 />,
    IconMale: <IconMale />,
    IconMapPin: <IconMapPin />,
    IconMapPinStroked: <IconMapPinStroked />,
    IconMarginLeftStroked: <IconMarginLeftStroked />,
    IconMarginStroked: <IconMarginStroked />,
    IconMark: <IconMark />,
    IconMaximize: <IconMaximize />,
    IconMember: <IconMember />,
    IconMenu: <IconMenu />,
    IconMicrophone: <IconMicrophone />,
    IconMicrophoneOff: <IconMicrophoneOff />,
    IconMinimize: <IconMinimize />,
    IconMinus: <IconMinus />,
    IconMinusCircle: <IconMinusCircle />,
    IconMinusCircleStroked: <IconMinusCircleStroked />,
    IconMinusStroked: <IconMinusStroked />,
    IconModalStroked: <IconModalStroked />,
    IconMoneyExchangeStroked: <IconMoneyExchangeStroked />,
    IconMonitorStroked: <IconMonitorStroked />,
    IconMoon: <IconMoon />,
    IconMore: <IconMore />,
    IconMoreStroked: <IconMoreStroked />,
    IconMusic: <IconMusic />,
    IconMusicNoteStroked: <IconMusicNoteStroked />,
    IconMute: <IconMute />,
    IconNineGridStroked: <IconNineGridStroked />,
    IconNoteMoneyStroked: <IconNoteMoneyStroked />,
    IconOption: <IconOption />,
    IconOrderedList: <IconOrderedList />,
    IconOrderedListStroked: <IconOrderedListStroked />,
    IconPaperclip: <IconPaperclip />,
    IconPause: <IconPause />,
    IconPercentage: <IconPercentage />,
    IconPhone: <IconPhone />,
    IconPhoneStroke: <IconPhoneStroke />,
    IconPieChart2Stroked: <IconPieChart2Stroked />,
    IconPieChartStroked: <IconPieChartStroked />,
    IconPiechartH5Stroked: <IconPiechartH5Stroked />,
    IconPipixiaLogo: <IconPipixiaLogo />,
    IconPlay: <IconPlay />,
    IconPlayCircle: <IconPlayCircle />,
    IconPlus: <IconPlus />,
    IconPlusCircle: <IconPlusCircle />,
    IconPlusCircleStroked: <IconPlusCircleStroked />,
    IconPlusStroked: <IconPlusStroked />,
    IconPriceTag: <IconPriceTag />,
    IconPrint: <IconPrint />,
    IconPrizeStroked: <IconPrizeStroked />,
    IconPulse: <IconPulse />,
    IconPuzzle: <IconPuzzle />,
    IconQingyan: <IconQingyan />,
    IconQrCode: <IconQrCode />,
    IconQuit: <IconQuit />,
    IconQuote: <IconQuote />,
    IconRadio: <IconRadio />,
    IconRankingCardStroked: <IconRankingCardStroked />,
    IconRealSizeStroked: <IconRealSizeStroked />,
    IconRedo: <IconRedo />,
    IconRedoStroked: <IconRedoStroked />,
    IconRefresh: <IconRefresh />,
    IconRefresh2: <IconRefresh2 />,
    IconRegExp: <IconRegExp />,
    IconReply: <IconReply />,
    IconReplyStroked: <IconReplyStroked />,
    IconResso: <IconResso />,
    IconRestart: <IconRestart />,
    IconRingChartStroked: <IconRingChartStroked />,
    IconRotate: <IconRotate />,
    IconRotationStroked: <IconRotationStroked />,
    IconRoute: <IconRoute />,
    IconRowsStroked: <IconRowsStroked />,
    IconSafe: <IconSafe />,
    IconSave: <IconSave />,
    IconSaveStroked: <IconSaveStroked />,
    IconScan: <IconScan />,
    IconScissors: <IconScissors />,
    IconSearch: <IconSearch />,
    IconSearchStroked: <IconSearchStroked />,
    IconSectionStroked: <IconSectionStroked />,
    IconSemiLogo: <IconSemiLogo />,
    IconSend: <IconSend />,
    IconSendMsgStroked: <IconSendMsgStroked />,
    IconSendStroked: <IconSendStroked />,
    IconServer: <IconServer />,
    IconServerStroked: <IconServerStroked />,
    IconSetting: <IconSetting />,
    IconSettingStroked: <IconSettingStroked />,
    IconShareMoneyStroked: <IconShareMoneyStroked />,
    IconShareStroked: <IconShareStroked />,
    IconShield: <IconShield />,
    IconShieldStroked: <IconShieldStroked />,
    IconShift: <IconShift />,
    IconShoppingBag: <IconShoppingBag />,
    IconShrink: <IconShrink />,
    IconShrinkScreenStroked: <IconShrinkScreenStroked />,
    IconSidebar: <IconSidebar />,
    IconSignal: <IconSignal />,
    IconSimilarity: <IconSimilarity />,
    IconSmallTriangleDown: <IconSmallTriangleDown />,
    IconSmallTriangleLeft: <IconSmallTriangleLeft />,
    IconSmallTriangleRight: <IconSmallTriangleRight />,
    IconSmallTriangleTop: <IconSmallTriangleTop />,
    IconSmartphoneCheckStroked: <IconSmartphoneCheckStroked />,
    IconSmartphoneStroked: <IconSmartphoneStroked />,
    IconSong: <IconSong />,
    IconSonicStroked: <IconSonicStroked />,
    IconSort: <IconSort />,
    IconSortStroked: <IconSortStroked />,
    IconSourceControl: <IconSourceControl />,
    IconSpin: <IconSpin />,
    IconStackBarChartStroked: <IconStackBarChartStroked />,
    IconStar: <IconStar />,
    IconStarStroked: <IconStarStroked />,
    IconStop: <IconStop />,
    IconStopwatchStroked: <IconStopwatchStroked />,
    IconStrikeThrough: <IconStrikeThrough />,
    IconSun: <IconSun />,
    IconSync: <IconSync />,
    IconTabArrowStroked: <IconTabArrowStroked />,
    IconTabsStroked: <IconTabsStroked />,
    IconTaskMoneyStroked: <IconTaskMoneyStroked />,
    IconTemplate: <IconTemplate />,
    IconTemplateStroked: <IconTemplateStroked />,
    IconTerminal: <IconTerminal />,
    IconTestScoreStroked: <IconTestScoreStroked />,
    IconText: <IconText />,
    IconTextRectangle: <IconTextRectangle />,
    IconTextStroked: <IconTextStroked />,
    IconThumbUpStroked: <IconThumbUpStroked />,
    IconTick: <IconTick />,
    IconTickCircle: <IconTickCircle />,
    IconTicketCodeExchangeStroked: <IconTicketCodeExchangeStroked />,
    IconTicketCodeStroked: <IconTicketCodeStroked />,
    IconTiktokLogo: <IconTiktokLogo />,
    IconTop: <IconTop />,
    IconTopCenterStroked: <IconTopCenterStroked />,
    IconTopLeftStroked: <IconTopLeftStroked />,
    IconTopRightStroked: <IconTopRightStroked />,
    IconTopbuzzLogo: <IconTopbuzzLogo />,
    IconToutiaoLogo: <IconToutiaoLogo />,
    IconTransparentStroked: <IconTransparentStroked />,
    IconTreeTriangleDown: <IconTreeTriangleDown />,
    IconTreeTriangleRight: <IconTreeTriangleRight />,
    IconTriangleArrow: <IconTriangleArrow />,
    IconTriangleArrowVertical: <IconTriangleArrowVertical />,
    IconTriangleDown: <IconTriangleDown />,
    IconTriangleUp: <IconTriangleUp />,
    IconTrueFalseStroked: <IconTrueFalseStroked />,
    IconTvCheckedStroked: <IconTvCheckedStroked />,
    IconTwitter: <IconTwitter />,
    IconTypograph: <IconTypograph />,
    IconUnChainStroked: <IconUnChainStroked />,
    IconUnderline: <IconUnderline />,
    IconUndo: <IconUndo />,
    IconUnlink: <IconUnlink />,
    IconUnlock: <IconUnlock />,
    IconUnlockStroked: <IconUnlockStroked />,
    IconUpload: <IconUpload />,
    IconUploadError: <IconUploadError />,
    IconUser: <IconUser />,
    IconUserAdd: <IconUserAdd />,
    IconUserCardPhone: <IconUserCardPhone />,
    IconUserCardVideo: <IconUserCardVideo />,
    IconUserCircle: <IconUserCircle />,
    IconUserCircleStroked: <IconUserCircleStroked />,
    IconUserGroup: <IconUserGroup />,
    IconUserListStroked: <IconUserListStroked />,
    IconUserSetting: <IconUserSetting />,
    IconUserStroked: <IconUserStroked />,
    IconVennChartStroked: <IconVennChartStroked />,
    IconVerify: <IconVerify />,
    IconVideo: <IconVideo />,
    IconVideoDouyinStroked: <IconVideoDouyinStroked />,
    IconVideoListStroked: <IconVideoListStroked />,
    IconVideoStroked: <IconVideoStroked />,
    IconVideoUrlStroked: <IconVideoUrlStroked />,
    IconVigoLogo: <IconVigoLogo />,
    IconVolume1: <IconVolume1 />,
    IconVolume2: <IconVolume2 />,
    IconVolumnSilent: <IconVolumnSilent />,
    IconVoteStroked: <IconVoteStroked />,
    IconVoteVideoStroked: <IconVoteVideoStroked />,
    IconWeibo: <IconWeibo />,
    IconWholeWord: <IconWholeWord />,
    IconWifi: <IconWifi />,
    IconWindowAdaptionStroked: <IconWindowAdaptionStroked />,
    IconWrench: <IconWrench />,
    IconXiguaLogo: <IconXiguaLogo />,
    IconYoutube: <IconYoutube />,
}

export default icon