services:
  nginx:
    image: nginx
    container_name: nginx:stable-alpine
    networks:
      - simple
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    ports:
      - 80:80
    depends_on: # 依赖顺序等待服务启动完成在启动代理
     - auth
     - simple

  redis:
    image: redis:alpine3.16
    container_name: redis
    networks:
      - simple
    ports:
      - 6379:6379
  
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    networks:
      - simple
    environment:
      MYSQL_ROOT_PASSWORD: dd666666
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  auth:
    build:
      context: ../src/auth/Simple.Auth.HttpApi.Host/
      dockerfile: .
    container_name: auth
    depends_on: # 依赖顺序等待MySQL redis启动完成在启动服务
     - mysql
     - redis

  simple:
    build:
      context: ../src/Simple.HttpApi.Host/
      dockerfile: .
    container_name: simple
    depends_on: # 依赖顺序等待MySQL redis启动完成在启动服务
     - mysql
     - redis

networks:
  simple:
    driver: bridge